#!/usr/bin/python

from subprocess import call
from pathlib import Path
import json
import os
import shutil
import sys

version = "v0.1.1"

# Avoid logic if just calling help/usage dialog
if len(sys.argv) == 2 and sys.argv[1] in ("-h", "--help"):
    print(
"""Usage: quicktrack [ALIAS]

When ALIAS supplied and in config.json, inject icuuc.dll and run OpenTrack within game.

With no ALIAS, show available games.
  -h, --help      show this help dialog

Quicktrack {}, Breadfish47""".format(version))
    exit(0)

# Establish script directory to retrieve config file
dir = Path(__file__).resolve().parent
configPath = os.path.join(dir, "config.json")

try:
    with open(configPath, "r") as file:
        config = json.load(file)
except FileNotFoundError:
  print("Error: Config file not found")
except json.JSONDecodeError:
  print("Error: Invalid JSON in config file")

def printGames():
    print("Quicktrack {}".format(version))
    for game in config["games"]:
        print("-- {} / alias {}\n".format(game["name"], game["alias"]))

def injectTrack(alias):
    steamPath = config["steamPath"]
    if os.path.isdir(os.path.expanduser(steamPath)) == False:
        print("Error: steamPath invalid")
        exit(1)

    game = next((game for game in config["games"] if game["alias"] == alias), None)
    if game is None:
      print("Error: Alias not in config.json")
      exit(1)

    gamePath = os.path.expanduser(os.path.join(steamPath, "compatdata", game["appid"], "pfx/drive_c/windows/system32"))
    if os.path.exists(gamePath):
        if not os.path.isfile(os.path.join(gamePath, "icuuc.dll")):
            print("Inserting icuuc.dll for opentrack compatibility...")
            shutil.copyfile("icuuc.dll", os.path.join(gamePath, "icuuc.dll"))

        call("protontricks-launch --appid {} {}".format(game["appid"], os.path.join(dir, "install", "opentrack.exe")), shell=True)
        exit()
    else:
        print("Error: Game directory not found:\n {}".format(gamePath))
        exit(1)

if len(sys.argv) == 2:
  injectTrack(sys.argv[1])
else:
    printGames()
